---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: plugin-test-argocd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: plugin-test-argocd 
  name: plugin-test-argocd
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi