apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: plugin-test-argocd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: plugin-test-argocd 
  name: plugin-test-argocd
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: plugin-test-argocd 
