apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: plugin-test-argocd 
  janus-idp.io/tekton: plugin-test-argocd
  backstage.io/kubernetes-id: plugin-test-argocd
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: plugin-test-argocd
resources: 
- application-dev.yaml